# Configurazione principale del sito Governo Sierra V3
title: "Governo di Sierra V3"
description: "Portale istituzionale del Governo di Sierra V3"
url: ""
baseurl: "/site"
permalink: pretty

nav:
  - title: "Leggi"
    children:
      - title: "Carta di San Andreas"
        url: "/carta-di-san-andreas/"
      - title: "Codice Penale"
        url: "/codice-penale/"
      - title: "Codice di Procedura Penale"
        url: "/codice-procedura-penale/"
      - title: "Regolamento Attivit√† Private"
        url: "/regolamento-attivita-private/"
      - title: "Regolamento Avvocati"
        url: "/regolamento-avvocati/"
      - title: "Lista oggetti Proibibi/limitati"
        url: "/lista-oggetti-proibiti/"
  - title: "Cariche pubbliche"
    url: "/cariche-pubbliche/"
  - title: "Posizioni Aperte"
    url: "/posizioni-aperte/"
  - title: "Aziende"
    url: "/aziende/"
  - title: "Avvocati"
    url: "/avvocati/"
  - title: "Segnalazioni"
    url: "/segnalazioni/"

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - assets
